### ISSUE TITLE
NullReferenceException occurs when you put GTAV on the pause screen, change the song and restart the game

### ISSUE THREAD

**Issue by QuestDragon** [justalemon/WhatsPlaying#5]
### What version are you using?

1.0.0

### What were you trying to do?

As the title suggests, if you pause the game while riding in a vehicle, play another song, and then return to the game, an error will occur.

### What were you expecting to happen?

I thought the newly played song would be displayed when I returned from the pause screen, but an error occurred.

### What actually happened?

I apologize for the similar text, but contrary to my expectations, a NullReferenceException actually occurred. Looking at the log, it seems that it is occurring within OnTick.

### What are your system specifications?

OS: Windows 10 Pro 64 Bit 22H2
CPU: 13th Gen Intel(R) Core(TM) i9-13900KS   3.20 GHz
RAM: 128 GB
GPU: NVIDIA GeForce RTX 3090

### Anything else you might want to add?

I thought it was an interesting mod and downloaded it.
**I am Japanese, so I would appreciate it if you could respond to my Issue, which is translated by Google Translate.**
I would like to download and use the latest version when it is updated! Thank you very much.

**Comment by justalemon** [comment]
Hi, would you be willing to send the file called ScriptHookVDotNet.log? So I can see exactly where the problem is happening. Thanks!

**Comment by QuestDragon** [comment]
got it!  Unfortunately, I'm out of town right now, so I'll send it to you as soon as I get home!

**Comment by justalemon** [comment]
Okay, no problem. So far I have been unable to replicate it so I'm going to wait for your log file :)

**Comment by justalemon** [comment]
Scratch that, I managed to replicate it although the line doesn't makes sense. Ill take a deeper look.

![image](https://github.com/justalemon/WhatsPlaying/assets/11861253/776c86ca-4cdc-4f16-aac2-72d82fa8ef15)

**Comment by justalemon** [comment]
Fixed!

The problem was that some players instead of updating the playback information, they remove the current song information and create a new one.

**Comment by justalemon** [comment]
Side note: This probably affects all music players that run as web apps in Chromium based browsers.

**Comment by QuestDragon** [comment]
Thank you for the quick answer!  I'm sorry that I couldn't attach the log file after all... I'll definitely download the updated mod!

**Comment by justalemon** [comment]
If you want the fix as soon as possible, you can download the latest test build from the Actions Artifacts:

* Go to https://github.com/justalemon/WhatsPlaying/actions
* Click the last build with the green checkmark
* Scroll all the way down until you see this, click WhatsPlaying.Debug to get the latest development build
  ![image](https://github.com/justalemon/WhatsPlaying/assets/11861253/3ca42580-ff8c-4bee-83d1-0d8d20ba3ef5)
