### ISSUE TITLE
System.Exception: Remote procedure call failed. (Exception from HRESULT: 0x800706BE)

### ISSUE THREAD

**Issue by QuestDragon** [justalemon/WhatsPlaying#6]
### What version are you using?

366e22c

### What were you trying to do?

Hello, it's been a while, I have created [this Issue](https://github.com/justalemon/WhatsPlaying/issues/5) before.

When I change the song while paused and return to the game screen, the changes are indeed reflected, but now, conversely, when I end playback (e.g., exit the player application), I seem to get a NullReferenceException.... I am sure this is a problem...

### What were you expecting to happen?

I expected the song title and artist name text to be hidden.

### What actually happened?

After playing a song, going to the pause screen, and exiting the player application, when I returned to the game screen, a NullReferenceException occurred and the text was hidden _(actually the script crashed)_.

### What are your system specifications?

OS: Windows 10 Pro 64 Bit 22H2
CPU: 13th Gen Intel(R) Core(TM) i9-13900KS 3.20 GHz
RAM: 128 GB
GPU: NVIDIA GeForce RTX 3090

*_I apologize for the content being exactly the same as the previous issue..._

### Anything else you might want to add?

I would appreciate it if you could respond to this issue when you have time.

**Comment by justalemon** [comment]
Same exact exception or different?

**Comment by QuestDragon** [comment]
It has been a while.
Has there been any progress since then?

**Comment by WithLithum** [comment]
You will want to upload the entire log to diagnose the problem, although this indeed looks like P/Invoke problem of some sort, at least it came from the native part.
